name: WhatsApp Bot Local Environment

services:
  postgresql-db:
    image: postgres:18-alpine
    container_name: whatsapp-bot-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: whatsapp_bot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
