name: WhatsApp Bot Production Environment

services:
  postgresql-db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  prisma-migrator:
    image: ${WHATSAPP_BOT_IMAGE}:${WHATSAPP_BOT_TAG}
    depends_on:
      - postgresql-db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-db:5432/${POSTGRES_DB}?schema=public
    command: ["sh", "-c", "npx", "prisma", "migrate", "deploy"]

  whatsapp-bot:
    image: ${WHATSAPP_BOT_IMAGE}:${WHATSAPP_BOT_TAG}
    restart: always
    depends_on:
      postgresql-db:
        condition: service_started
      prisma-migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-db:5432/${POSTGRES_DB}?schema=public
      PORT: ${PORT}
      WHATSAPP_API_VERSION: ${WHATSAPP_API_VERSION}
      WHATSAPP_API_VERIFY_TOKEN: ${WHATSAPP_API_VERIFY_TOKEN}
      NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"

volumes:
  pgdata:
